/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<android/log.h>
/* Header for class robin_scaffold1_basic_security_jni_JniManager */

#ifndef _Included_robin_scaffold_basic_security_util_JNIUtils
#define _Included_robin_scaffold_basic_security_util_JNIUtils
#ifdef __cplusplus
#define TAG "robin_native" // 这个是自定义的LOG的标识
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG,TAG ,__VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,TAG ,__VA_ARGS__)
#define LOGW(...) __android_log_print(ANDROID_LOG_WARN,TAG ,__VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,TAG ,__VA_ARGS__)
#define LOGF(...) __android_log_print(ANDROID_LOG_FATAL,TAG ,__VA_ARGS__)
extern "C" {
#endif
static jclass contextClass;
static jclass signatureClass;
static jclass packageNameClass;
static jclass packageInfoClass;

/*
 * Class:     robin_scaffold_basic_security_jni_JniManager
 * Method:    getPublicKey
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_robin_scaffold_baisc_security_jni_JniManager_getPublicKey
  (JNIEnv *, jobject, jobject);

/*
 * Class:     robin_scaffold_basic_security_jni_JniManager
 * Method:    getSecret
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_robin_scaffold_baisc_security_jni_JniManager_getSecret
  (JNIEnv *, jobject, jobject);

  /*
   * Class:     robin_scaffold_basic_security_jni_JniManager
   * Method:    getDesKey
   * Signature: (Ljava/lang/String;)Ljava/lang/String;
   */
JNIEXPORT jstring JNICALL Java_robin_scaffold_baisc_security_jni_JniManager_getDesKey
    (JNIEnv *, jobject, jobject);



const char* getSignString(JNIEnv *,jobject);

void ByteToHexStr(char*, char*, int);

JNIEXPORT jint JNICALL JNI_OnLoad (JavaVM* ,void* );

#ifdef __cplusplus
}
#endif
#endif